// src/components/react/BasicTForm.tsx
import { basicFormSchema, type ExpectedBasicForm } from "../../lib/form.schema";
import { useAppForm } from "../../lib/tanstack.context";
import { RenderCount } from "./RenderCount";

let id = 0;

const BasicTForm = () => {
  const form = useAppForm({
    // Form type can be passed this way
    defaultValues: {
      name: "",
      description: "",
      bigL: false,
      losers: [],
    } as ExpectedBasicForm,
    validators: {
      // Accepts schemas without a separate lib
      onSubmit: basicFormSchema,
    },
    onSubmit: ({ value }) => {
      console.log(value);
    },
  });

  return (
    <form
      className="flex flex-col gap-2 w-full"
      onSubmit={(e) => {
        e.preventDefault();
        form.handleSubmit();
      }}
    >
      <div className="flex gap-2 items-center">
        <h3>Tanstack form</h3>
        <RenderCount />
      </div>
      {/* Form fields are typed here */}
      <form.Field name="name">
        {(field) => (
          <>
            <div className="flex gap-2 items-center">
              <label htmlFor={`tform-${field.name}`}>Name *</label>
              <RenderCount />
            </div>
            <input
              className="border-2"
              id={`tform-${field.name}`}
              name={field.name}
              value={field.state.value}
              onBlur={field.handleBlur}
              // Fields re-render twice on change for some reason,
              onChange={(e) => field.handleChange(e.target.value)}
            />
            {field.state.meta.errors.length > 0 &&
              field.state.meta.isTouched && (
                <div className="text-red-600">
                  {field.state.meta.errors.reduce(
                    (acc, curr) => (acc += curr?.message),
                    ""
                  )}
                </div>
              )}
          </>
        )}
      </form.Field>
      <form.AppField
        name="description"
        children={(field) => <field.TFormInput label="Description" />}
      />
      <form.Field name="bigL">
        {(field) => (
          <>
            <div className="flex gap-2 items-center">
              <label className="flex gap-2" htmlFor={`tform-${field.name}`}>
                <input
                  className="border-2"
                  id={`tform-${field.name}`}
                  name={field.name}
                  type="checkbox"
                  checked={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={(e) => field.handleChange(e.target.checked)}
                />
                Big L?
              </label>
              <RenderCount />
            </div>
            {field.state.meta.errors.length > 0 &&
              field.state.meta.isTouched && (
                <div className="text-red-600">
                  {field.state.meta.errors.reduce(
                    (acc, curr) => (acc += curr?.message),
                    ""
                  )}
                </div>
              )}
          </>
        )}
      </form.Field>

      <form.Field name="losers" mode="array">
        {(fieldApi) => (
          <>
            {fieldApi.state.value.map((field, index) => (
              <form.AppField name={`losers[${index}].name`} key={field.id}>
                {(field) => (
                  <div className="flex gap-2">
                    <field.TFormInput label={`Loser ${index + 1}`} />
                    <button
                      className="ms-auto relative overflow-hidden rounded-2xl bg-gradient-to-r from-purple-500 to-indigo-500 p-3 px-6 text-lg font-bold text-white shadow-lg transition-all duration-300 hover:scale-105 hover:shadow-2xl before:absolute before:inset-0 before:bg-white before:opacity-10 before:blur-lg"
                      type="button"
                      onClick={() => fieldApi.removeValue(index)}
                    >
                      Delete
                    </button>
                  </div>
                )}
              </form.AppField>
            ))}

            <button
              className="border-2"
              type="button"
              onClick={() => fieldApi.pushValue({ id: id++, name: "" })}
            >
              Add loser
            </button>
          </>
        )}
      </form.Field>

      <form.Subscribe selector={(state) => state.values.bigL}>
        {(bigLValue) =>
          bigLValue && (
            <div className="flex gap-2 items-center">
              <p className="text-2xl font-bold text-transparent bg-clip-text animate-gradient bg-linear-to-br from-purple-600 via-cyan-300 to-lime-400 bg-size-[50%_100%]">
                Amazin conditional render
              </p>
              <RenderCount />
            </div>
          )
        }
      </form.Subscribe>

      <button className="border-2" type="submit">
        Submit
      </button>
    </form>
  );
};

export default BasicTForm;

// src/components/angular/BasicTForm.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  inject,
  Injector,
} from "@angular/core";
import { injectForm, TanStackField } from "@tanstack/angular-form";
import { basicFormSchema, type ExpectedBasicForm } from "../../lib/form.schema";
@Component({
  selector: "basic-tform",
  template: `<form
    class="flex flex-col gap-2 w-full"
    (submit)="handleSubmit($event)"
  >
    <h3>Tanstack Form</h3>
    @if (form) {

    <div [tanstackField]="form" name="name" #name="field">
      <label class="block" [for]="'angular-tform-' + name.api.name"
        >Name *</label
      >
      <input
        class="border-2 w-full"
        [id]="'angular-tform-' + name.api.name"
        [name]="name.api.name"
        [value]="name.api.state.value"
        (blur)="name.api.handleBlur()"
        (input)="name.api.handleChange($any($event).target.value)"
      />
      @if (name.api.state.meta.isTouched) {
      <div class="text-red-600">
        {{ getErrors(name.api.state.meta.errors) }}
      </div>
      }
    </div>
    <div [tanstackField]="form" name="description" #description="field">
      <label class="block" [for]="'angular-tform-' + description.api.name"
        >Description</label
      >
      <input
        class="border-2 w-full"
        [id]="'angular-tform-' + description.api.name"
        [name]="description.api.name"
        [value]="description.api.state.value"
        (blur)="description.api.handleBlur()"
        (input)="description.api.handleChange($any($event).target.value)"
      />
    </div>
    <div [tanstackField]="form" name="bigL" #bigL="field">
      <label
        class="block"
        class="flex gap-2"
        [for]="'angular-tform-' + bigL.api.name"
      >
        <input
          class="border-2"
          type="checkbox"
          [id]="'angular-tform-' + bigL.api.name"
          [name]="bigL.api.name"
          [value]="bigL.api.state.value"
          (blur)="bigL.api.handleBlur()"
          (change)="bigL.api.handleChange($any($event).target.checked)"
        />
        Big L?
      </label>
      @if (bigL.api.state.meta.isTouched) {
      <div class="text-red-600">
        {{ getErrors(bigL.api.state.meta.errors) }}
      </div>
      }
    </div>

    <ng-container [tanstackField]="form" name="losers" #losers="field">
      @for (_ of losers.api.state.value; track index; let index = $index) {
      <ng-container
        [tanstackField]="form"
        [name]="getLoserName(index)"
        #loser="field"
      >
        <div class="flex gap-2">
          <div>
            <label class="block" [attr.htmlFor]="'angular-tform-loser-' + index"
              >Loser {{ index + 1 }}</label
            >
            <input
              [value]="loser.api.state.value"
              (blur)="loser.api.handleBlur()"
              (change)="loser.api.handleChange($any($event).target.value)"
              class="border-2"
              [id]="'angular-tform-loser-' + index"
            />
          </div>
          <button
            class="ms-auto relative overflow-hidden rounded-2xl bg-gradient-to-r from-purple-500 to-indigo-500 p-3 px-6 text-lg font-bold text-white shadow-lg transition-all duration-300 hover:scale-105 hover:shadow-2xl before:absolute before:inset-0 before:bg-white before:opacity-10 before:blur-lg"
            type="button"
            (click)="losers.api.removeValue(index)"
          >
            Delete
          </button>
        </div>
      </ng-container>
      }
      <button
        class="border-2"
        type="button"
        (click)="losers.api.pushValue(defaultLoser)"
      >
        Add loser
      </button>
    </ng-container>

    @if (form.state.values.bigL) {
    <p
      class="text-2xl font-bold text-transparent bg-clip-text animate-gradient bg-linear-to-br from-purple-600 via-cyan-300 to-lime-400 bg-size-[50%_100%]"
    >
      Amazin conditional render
    </p>
    }

    <button class="border-2" type="submit">Submit</button>
    }
  </form> `,
  imports: [TanStackField],
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: true,
})
export class BasicTFormComponent {
  injector = inject(Injector);
  cdr = inject(ChangeDetectorRef);
  form = injectForm({
    defaultValues: {
      name: "",
      description: "",
      bigL: false,
      losers: [],
    } as ExpectedBasicForm,
    onSubmit({ value }) {
      console.log(value);
    },
    validators: {
      onBlur: basicFormSchema,
    },
  });

  async handleSubmit(event: SubmitEvent) {
    console.log(this.form);
    event.preventDefault();
    event.stopPropagation();
    if (this.form) {
      // Would like to have all validations run on submit...
      await this.form.handleSubmit();
      this.cdr.detectChanges();
    }
  }

  defaultLoser = {
    name: "",
    id: 0,
  };
  getLoserName = (index: number) => `losers[${index}].name` as const;

  getErrors(errors: { message?: string }[]) {
    return errors.reduce((acc, curr) => (acc += curr?.message), "");
  }
}
